// Keep this plain so Vite can import it without loading React or the content modules.
export const contentSlugs = [
  'example',
  'tyre-badge',
  'sector-times',
  'driver-name-plate',
  'start-lights',
  'timing-tower',
  'replay-bumper',
  'lap-counter',
  'race-clock',
  'flag-banner',
  'overtake-indicator',
  'podium',
  'track-map',
  'stint-bar',
  'gap-chart',
  'speed-trap',
  'gauge',
  'team-radio',
  'pit-stop-card',
  'battle-card',
] as const;
