import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { pathFromPoints } from '../registry/boxbox/ui/track-map.tsx';

/**
 * Generates `src/data/circuits.ts` from bacinger/f1-circuits (MIT), one GeoJSON
 * LineString per venue. Run with `bun run circuits:build`.
 *
 * The outlines are projected with a plain equirectangular projection (longitude
 * scaled by the cosine of the mean latitude, so a metre is a metre on both axes),
 * then fitted into a 1000-wide viewBox whose height follows the circuit's own
 * aspect ratio. The first point of each LineString is taken as start/finish.
 */
const SOURCE = 'https://raw.githubusercontent.com/bacinger/f1-circuits/master/circuits';

/** The 2026 calendar, in season order. */
const CALENDAR_2026 = [
  'au-1953',
  'cn-2004',
  'jp-1962',
  'bh-2002',
  'sa-2021',
  'us-2022',
  'ca-1978',
  'mc-1929',
  'es-1991',
  'at-1969',
  'gb-1948',
  'be-1925',
  'hu-1986',
  'nl-1948',
  'it-1922',
  'es-2026',
  'az-2016',
  'sg-2008',
  'us-2012',
  'mx-1962',
  'br-1940',
  'us-2023',
  'qa-2004',
  'ae-2009',
] as const;

/** The source lists these in the wrong direction of travel; the point order is reversed. */
const REVERSED = new Set<string>(['sg-2008']);

const WIDTH = 1000;
const MIN_HEIGHT = 450;
const MAX_HEIGHT = 800;

type Feature = {
  properties: { id: string; Name: string; Location: string; length: number };
  geometry: { type: 'LineString'; coordinates: [number, number][] };
};
type FeatureCollection = { features: Feature[] };

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.resolve(__dirname, '..', 'src', 'data', 'circuits.ts');

async function fetchCircuit(id: string): Promise<Feature> {
  const response = await fetch(`${SOURCE}/${id}.geojson`);
  if (!response.ok) throw new Error(`${id}: HTTP ${response.status}`);
  const collection = (await response.json()) as FeatureCollection;
  const feature = collection.features[0];
  if (!feature || feature.geometry.type !== 'LineString') {
    throw new Error(`${id}: expected one LineString feature`);
  }
  return feature;
}

function project(coordinates: [number, number][], reversed: boolean): [number, number][] {
  let points = coordinates;
  const [first] = points;
  const last = points.at(-1);
  // A closed LineString repeats its first point; `pathFromPoints` closes with `Z` instead.
  if (first && last && first[0] === last[0] && first[1] === last[1]) points = points.slice(0, -1);
  if (reversed) {
    // Keep the same start/finish point, reverse the direction of travel.
    const [start, ...rest] = points;
    points = start ? [start, ...rest.reverse()] : points;
  }
  const meanLat = points.reduce((sum, [, lat]) => sum + lat, 0) / points.length;
  const k = Math.cos((meanLat * Math.PI) / 180);
  return points.map(([lon, lat]) => [lon * k, lat]);
}

function fit(points: [number, number][]) {
  const xs = points.map(([x]) => x);
  const ys = points.map(([, y]) => y);
  const spanX = Math.max(...xs) - Math.min(...xs);
  const spanY = Math.max(...ys) - Math.min(...ys);
  const height = Math.min(MAX_HEIGHT, Math.max(MIN_HEIGHT, Math.round((WIDTH * spanY) / spanX)));
  return pathFromPoints(points, { width: WIDTH, height, padding: 40 });
}

async function main() {
  const circuits = [];
  for (const id of CALENDAR_2026) {
    const feature = await fetchCircuit(id);
    const { d, viewBox } = fit(project(feature.geometry.coordinates, REVERSED.has(id)));
    circuits.push({
      id,
      name: feature.properties.Name,
      location: feature.properties.Location,
      lengthM: feature.properties.length,
      d,
      viewBox,
    });
    process.stdout.write(`${id} ${feature.properties.Name} (${viewBox})\n`);
  }

  const body = circuits
    .map(
      (c) =>
        `  {\n    id: ${JSON.stringify(c.id)},\n    name: ${JSON.stringify(c.name)},\n    location: ${JSON.stringify(c.location)},\n    lengthM: ${c.lengthM},\n    viewBox: ${JSON.stringify(c.viewBox)},\n    d: ${JSON.stringify(c.d)},\n  }`,
    )
    .join(',\n');

  const source = `// Generated by \`bun run circuits:build\` from bacinger/f1-circuits (MIT). Do not edit.
//
// Circuit layouts are the intellectual property of their venues. This project is
// unofficial and not affiliated with any racing series, circuit, or team.

export type Circuit = {
  id: string;
  name: string;
  location: string;
  /** Official lap length in metres, from the source data. */
  lengthM: number;
  viewBox: string;
  /** SVG \`d\` in \`viewBox\` units. Start/finish is the first point; travel follows path order. */
  d: string;
};

export const CIRCUITS: readonly Circuit[] = [
${body},
];

export const circuitById = (id: string) => CIRCUITS.find((circuit) => circuit.id === id);
`;

  await writeFile(outFile, source);
  process.stdout.write(
    `wrote ${path.relative(process.cwd(), outFile)} (${circuits.length} circuits)\n`,
  );
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exit(1);
});
