// Generated by `bun run circuits:elevation`. Do not edit.
//
// No circuit has elevation yet: `bun run circuits:elevation` samples it.

import type { ElevationSource } from './elevation-sources';

export type CircuitElevation = {
  source: ElevationSource;
  /**
   * Metres above the lap's lowest point, smoothed (`src/lib/elevation.ts`), evenly spaced round
   * the closed lap: entry `j` at the share `j / length` of the outline's distance.
   */
  heights: readonly number[];
};

/** Each circuit's elevation, by its id in `circuits.ts`. A circuit without one is flat. */
export const CIRCUIT_ELEVATION: Readonly<Partial<Record<string, CircuitElevation>>> = {};
